### ISSUE TITLE
typo in website

### ISSUE THREAD

**Issue by pborreli** [sibbell/sibbell-issues#1]
notfications -> notifications

**Comment by davegaeddert** [comment]
Thank you @pborreli! I assume the typo you're talking about specifically is the first sentence on the homepage? Are there any others that you found? I hate to think how long that's been like that...

![image](https://cloud.githubusercontent.com/assets/649496/6094400/2e444fd8-aeee-11e4-88af-f5e3b2f47794.png)

**Comment by pborreli** [comment]
@davegaeddert yes that was this one, don't worry I usually see typos others don't :smile:
