### ISSUE TITLE
Add RSS feed option instead of email

### ISSUE THREAD

**Issue by davidchiles** [sibbell/sibbell-issues#13]

**Comment by davegaeddert** [comment]
Thanks for the suggestion @davidchiles, I've been thinking the same thing and hopefully I'll have something to show you soon.

**Comment by davegaeddert** [comment]
@davidchiles do you have a preference when it comes to RSS vs an Atom feed?

**Comment by davidchiles** [comment]
I guess I lean towards Atom but not a strong preference.

**Comment by davegaeddert** [comment]
@davidchiles sorry this is taking so long, I've actually been using it myself and getting mixed results. What do you use for a feed reader?

**Comment by davidchiles** [comment]
@davegaeddert  no rush, I use Feedly.

**Comment by davegaeddert** [comment]
Ok @davidchiles, this is up and running! You should see it on https://sibbell.com/settings. Let me know if you have any questions or issues.
