### ISSUE TITLE
How do you force Sibbel to update the state of your starred Repos from GitHub?

### ISSUE THREAD

**Issue by acusti** [sibbell/sibbell-issues#16]
I tried disabling notifications for starred repos, then reenabling them. My current issue is have recently done some repo unstarring to cull my starred repos (I’ve been overwhelmed by notifications, which has inspired me to do some much needed spring cleaning), but those repos are still listed as starred in Sibbell.

**Comment by davegaeddert** [comment]
Hey @acusti, thanks for bringing this up. I had this on my list of things to clean up for a while but never got around to it. I think it should be good now.
