### ISSUE TITLE
Including Release Notes

### ISSUE THREAD

**Issue by mfcovington** [sibbell/sibbell-issues#18]
It would be really convenient if the release notes were included in the emails notifications. It seems like the earliest release emails I received may have had this, but no longer.

**Comment by davegaeddert** [comment]
Thanks @mfcovington, looks like you're right -- the release notes seem to be hit and miss at the moment.  I'll try and figure out what is happening here, it is much better when they have them!

**Comment by davegaeddert** [comment]
Hey @mfcovington, I think this should be fixed now. Let me know if not?!

**Comment by mfcovington** [comment]
It is now working as expected for me. Thanks!
