### ISSUE TITLE
delete account

### ISSUE THREAD

**Issue by Schweinepriester** [sibbell/sibbell-issues#19]
like  #14

thing is, i deactivated everything and still received mails, went further and revoked access from github, but still mails...

so, since there seems no other way, please delete my account :)

great service though!

**Comment by davegaeddert** [comment]
Sorry to hear that @Schweinepriester! I've deleted your account.

Sibbell does a lot of background task processing to try and keep everything up to date with GitHub. There's been a pretty good increase in traffic lately so my guess is that some emails still made it out before your deactivated settings got fully changed.

I've got a couple changes coming soon that should fix some of this -- including the ability to disable all emails with one switch. If you decide to come back, just log in again ;) Thanks.
