### ISSUE TITLE
can not visit https://sibbell.com/start/

### ISSUE THREAD

**Issue by sinchb** [sibbell/sibbell-issues#20]
When I visited your website, I got an error: Server Error (500)

**Comment by viegelinsch** [comment]
same to me.

**Comment by davegaeddert** [comment]
Hey @viegelinsch, I think the problem was that Sibbell was exceeding the GitHub API rate limits. You might try it again if you haven't already.

**Comment by viegelinsch** [comment]
I'm very sorry I tried it now and yesterday around 22:00 UTC. Result allways the same: not working. :-(

**Comment by davegaeddert** [comment]
Sorry about that, I think the OAuth with GitHub got messed up somehow. I deleted your accounts (there were like 5). If you try logging in again now, it **should** work. Let me know if not!

**Comment by viegelinsch** [comment]
now it works. THANK you!
