### ISSUE TITLE
Too many notifications, no ability to disable notifications, no ability to deactivate account

### ISSUE THREAD

**Issue by sparanoid** [sibbell/sibbell-issues#22]

**Comment by devatrox** [comment]
Please fix this. I disabled everything in the settings and even removed the Github connection but continue getting bombarded with emails. The "unsubscribe" link in the emails seem to do nothing.

**Comment by davegaeddert** [comment]
Hey @sparanoid and @devatrox. Sorry for any hassle this has caused. We're making some backend changes to deal with the traffic (some settings aren't getting propagated through quickly enough, and emails are getting out while the changes are still being saved).

I added a setting to disable all emails, immediately. You can find it here: https://sibbell.com/settings/
**I disabled emails for both of your accounts.** You can log in to re-enable them if you'd like.

@devatrox, thanks for pointed out the unsubscribe link -- I've created an issue for that here: #23.
