### ISSUE TITLE
Unlinked from Github Account - Still Getting Emails

### ISSUE THREAD

**Issue by lucanos** [sibbell/sibbell-issues#24]
I unlinked Sibbell from my Github account, thinking this would deactivate my Sibbell account. Nope. Got a pile of emails coming through, and no obvious way to terminate/delete my Sibbell account.

**Comment by davegaeddert** [comment]
Hey @lucanos, sorry if you got emails you didn't want! I went ahead and disabled emails entirely on your account. You can re-enable it on https://sibbell.com/settings/ if you'd like.

As far as deleting your account, you're right, there's no way to do that right now and unlinking from GitHub doesn't do it. I'll try and get this added soon - #25. In the meantime, if you want me to delete your account for you, just let me know.

**Comment by lucanos** [comment]
Hey Dave,

If you could kill my account, that would be terrific. I was taste-testing
Sibbell, and whilst I can see a value in it when working in GitHub as a
primary tool (unlike a GitHub consumer, like myself, where most repos I
watch are projects I download from time to time), I don't think it's the
right fit for me at the moment.

Thanks!
Luke

**Comment by davegaeddert** [comment]
Ok, I deleted your account. Thanks for the feedback/explanation! It's always nice to hear what people are looking for and why Sibbell may or may not be the right tool for them. It's still in the early stages and I'm always thinking about what the next steps should be. If you have any specific ideas, don't hesitate to let me know!
