### ISSUE TITLE
only 20 most recent releases

### ISSUE THREAD

**Issue by ltdeta** [sibbell/sibbell-issues#30]
How can i see the last release from all  watching repos on GitHub ?

**Comment by davegaeddert** [comment]
There's a redesign in the works, but for now I added a link at the bottom of the 20 most recent to view all releases. Hope that does what you're looking for!

![image](https://cloud.githubusercontent.com/assets/649496/9838734/0ca40340-5a2a-11e5-807c-b5103578ef49.png)

**Comment by ltdeta** [comment]
perfect!
