### ISSUE TITLE
How to quickly turn off repos?

### ISSUE THREAD

**Issue by laike9m** [sibbell/sibbell-issues#33]
I just want to get email notification for one repo, I don't care about other repos. Do I have to turn off other repos one by one? Is there a better way?

**Comment by davegaeddert** [comment]
Hey @laike9m, you might try going to the settings screen, disabling the sync starred and sync watching and hit save. Give it a second to make the changes (there's some background processing to do), then go to https://sibbell.com/github/repos/ and they should all be "off", allowing you to just enable the one.

Let me know if that doesn't work!

**Comment by laike9m** [comment]
Greate, it works. Thx @davegaeddert.
