### ISSUE TITLE
No emails since sept 9th, since starring google/material-design-icons

### ISSUE THREAD

**Issue by adam-knights** [sibbell/sibbell-issues#34]
Hi,

The last release email I received was for npm/npm v3.3.2 on September 9th. Looking at https://sibbell.com/github/recent/ I should have had emails for mike-north/ember-cli-materialize, emberjs/data, yapplabs/ember-modal-dialog, npm/npm v3.3.3 and expressjs/body-parser.

I starred one repo near straight after the 9th - google/material-design-icons, incase that helps and was the cause?

**Comment by davegaeddert** [comment]
Hey @adam-knights, sorry if something doesn't seem to be working. Thanks for the details -- I'll look into this.

**Comment by adam-knights** [comment]
Thanks @davegaeddert - any update on this? - been on holiday for a week and still no more release emails. Looking at https://sibbell.com/github/recent/ I would have expected 9.

**Comment by adam-knights** [comment]
If you want I could try unstarring the google repo to see if that fixes it?

**Comment by adam-knights** [comment]
Unstarring it did not make a difference

**Comment by davegaeddert** [comment]
Ok, thanks for pushing on this. Sorry, I've just been a little too busy lately. I think I actually found a small bug that was causing your problem (at some point your account got marked as "inactive" for some reason).

It should be fixed shortly and hopefully you'll be receiving emails from here on out!

If you ever sign up for one of the paid plans, let me know and I'll be sure to give you some kind of discount. Also bug me if in the several days you feel like you didn't get emails for releases that you should have.

**Comment by adam-knights** [comment]
Got my first email overnight so can confirm all good now.
