### ISSUE TITLE
Delay before Sibbell sees new releases?

### ISSUE THREAD

**Issue by BobDankert** [sibbell/sibbell-issues#42]
What is the expected delay before one of the repos I'm watching will notify me of a new release? I ask because I was surprised to see that the repo has had 4 updates in the past 2-3 days, and I haven't received notification of any of the releases. In fact, Sibbell still reports the repo is 0.9.0, when it is currently at 0.9.4. If this type of delay is normal, I'm just curious what "normal" is, since it doesn't seem to be documented anywhere (BTW - a FAQ page would be nice!)

**Comment by davegaeddert** [comment]
Hey @BobDankert, thanks for asking. Sibbell has to poll GitHub to get new release information, which happens about every 8 hours. Unfortunately we ran into some issues over the last few days related to this issue, and things weren't running as scheduled: https://github.com/sibbell/sibbell-issues/issues/40 So, that being said, normally you should receive release emails on the same day they are published. Hopefully now we're back up and running.

And you're right, there should be an FAQ page! I started an issue for that here: https://github.com/sibbell/sibbell-issues/issues/43

Thanks!
