### ISSUE TITLE
Notificactions

### ISSUE THREAD

**Issue by mribichich** [sibbell/sibbell-issues#54]
Hi there, It's been a while since I dont receive a mail notification. I was using sibbell since a lot of time, and in one moment it stop working for me. 

And every time I try to enter the settings page in sibbell it returns 500 code error.

how could I do to fix it?

thanks!

**Comment by kevindb** [comment]
+1

**Comment by gregthebusker** [comment]
I haven't received a single notification since Aug 31st.  Is Sibbell no longer in service?

**Comment by davegaeddert** [comment]
Hey guys sorry for the issues. This is a side-project for me and I'm still trying to find some time to devote to it, but it should be back up and running again. Let me know if you have further issues.

**Comment by nadeemja** [comment]
Apologies, Dave, for reopening this. Sibbell is the only service that does what it does. Not having it watch releases for me has been frustrating. At the moment, I don't need the paid features of sibbell. However, I would like to pay for this service, as it is so important. Please consider making sibbell paid-only, to ensure development. Thanks :)

**Comment by davegaeddert** [comment]
No problem @nadeemja. Thanks for the comment. It is incredibly encouraging to see how badly people still want to use Sibbell, despite the instability it's had for a little while now. I will definitely do some thinking on the best next steps for giving this the attention it deserves!

**Comment by nadeemja** [comment]
Hi again @davegaeddert 

SIbbell is inoperative again. No more notifications. Error on settings page.

If you're open to it, I would like to help out with Sibbell pro bono, even if you decide to make it a paid service (which I hope you do).

**Comment by davegaeddert** [comment]
@nadeemja thanks for the heads up, and for the offer. I'll certainly keep it in mind. At the moment, everyone's comments here has been enough to get me moving on this a little quicker than I was planning. I hope to have news to share as soon as possible!
