### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by lunarthegrey** [sibbell/sibbell-issues#55]
When I authenticate with my GitHub account it returns me to https://sibbell.com/start/ and I get a "Server Error (500)".

**Comment by davegaeddert** [comment]
This should be back up and running. Sorry for the issues -- this is a side project for me and I can't always give it the time it deserves right now. Hoping to soon though.

If you have any more issues leave a comment.

**Comment by lunarthegrey** [comment]
Thanks for fixing it, but now it seems the site is down

![screenshot_2016-09-19_22-05-36](https://cloud.githubusercontent.com/assets/8747426/18655274/7255fecc-7eb5-11e6-9524-7c2beab98f15.png)

**Comment by davegaeddert** [comment]
@lunarthegrey thanks for the heads up. Server must be swamped with tasks. I'll try and keep an eye on it.
