### ISSUE TITLE
Sibbell Down

### ISSUE THREAD

**Issue by rgfx** [sibbell/sibbell-issues#57]
I was missing Sibbell, how long has it been down for? Are there any alternatives?

http://downforeveryoneorjustme.com/sibbell.com

**Comment by davegaeddert** [comment]
@rgfx, sorry for the trouble. It's been a little hit and miss lately but we're trying to keep it up. We're planning a major overhaul (both performance and feature-wise) so hopefully soon it will be better than ever!
